# Generated by Django 6.0 on 2025-12-30 08:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='biographie',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='death_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='website',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.RegexValidator(code='invalid_https', message="URL must be strat with 'https://'.", regex='^https://')]),
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('first_name', 'last_name')},
        ),
    ]
