# Generated by Django 6.0 on 2025-12-30 08:39

import books.models
import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_author_biographie_author_death_date_author_website_and_more'),
        ('books', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='categories.category'),
        ),
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 30, 8, 39, 55, 41060, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='disponibility_counter',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'The disponibility counter cannot be less than 0')]),
        ),
        migrations.AddField(
            model_name='book',
            name='editor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='page_number',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'The page number cannot be less than 0')]),
        ),
        migrations.AddField(
            model_name='book',
            name='published_language',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'The quantity cannot be less than 0')]),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='authors.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='0000000000000', max_length=13, unique=True, validators=[django.core.validators.MinLengthValidator(13, 'ISBN_13 must contain exactly 13 characters')]),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_at',
            field=models.DateTimeField(validators=[books.models.Book.validate_published_year]),
        ),
    ]
