# Generated by Django 6.0 on 2025-12-30 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_book_category_book_created_at_book_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=350, blank=True)),
                ('nbr_library_card', models.CharField()),
                ('loaner_name', models.CharField(max_length=50)),
                ('loaner_email', models.EmailField(max_length=254)),
                ('loaned_at', models.DateTimeField(null=True)),
                ('should_be_returned_at', models.DateTimeField(null=True)),
                ('returned_at', models.DateTimeField(null=True)),
                ('state', models.CharField(choices=[('LOAN', 'Loan'), ('AVAILABLE', 'Available')], default='AVAILABLE')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='books.book')),
            ],
        ),
    ]
